services:

  service:
    image: gestiondeprojet-loginapp
    ports:
      - "8081:8081"
    networks:
      - lb-net
    environment:
      HOSTNAME: service

  registery:
    image: gestiondeprojet-loginapp
    networks:
      - lb-net
    environment:
      HOSTNAME: registery

  loadBalancer:
    image: gestiondeprojet-loginapp
    networks:
      - lb-net
    environment:
      HOSTNAME: loadBalancer

  node:
    image: gestiondeprojet-node:latest
    privileged: true
    ports:
      - "2375:2375"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
    networks:
      - lb-net
    environment:
      HOSTNAME: node


  worker1:
    image: gestiondeprojet-loginapp
    networks:
      - lb-net
    environment:
      HOSTNAME: worker1

  worker2:
    image: gestiondeprojet-loginapp
    networks:
      - lb-net
    environment:
      HOSTNAME: worker2
      
  worker3:
    image: gestiondeprojet-loginapp
    networks:
      - lb-net
    environment:
      HOSTNAME: worker3

networks:
  lb-net:
    driver: bridge