services:

  registery:
    build:
      context: .
    image: gestiondeprojet-loginapp
    ports:
      - "8081:8081"
    networks:
      - lb-net
    environment:
      HOSTNAME: registery

  loadBalancer:
    build:
      context: .
    image: gestiondeprojet-loginapp
    networks:
      - lb-net
    environment:
      HOSTNAME: loadBalancer

  worker1:
    build:
      context: .
    image: gestiondeprojet-loginapp
    networks:
      - lb-net
    environment:
      HOSTNAME: worker1

  worker2:
    build:
      context: .
    image: gestiondeprojet-loginapp
    networks:
      - lb-net
    environment:
      HOSTNAME: worker2
  worker3:
  
    build:
      context: .
    image: gestiondeprojet-loginapp
    networks:
      - lb-net
    environment:
      HOSTNAME: worker3

networks:
  lb-net:
    driver: bridge